version: "3.5"
services:

  backend:
    build: example-backend/
    image: backend
    container_name: backend
    environment:
      - REDIS_HOST=redis
      - REQUEST_ORIGIN=http://localhost
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DATABASE=postgres #POSTGRES_DB
      - POSTGRES_HOST=postgres #service name
    depends_on:
      - redis
      - postgres
      
  frontend:
    build: example-frontend/
    image: frontend
    container_name: frontend
    environment: 
      - REACT_APP_BACKEND_URL=http://localhost/api/
    depends_on:
      - backend
      
  redis:
    image: redis
    container_name: redis

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres
    container_name: db_postgres

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend
