version: "3.5"
services:

  backend:
    build: backend/
    image: backend
    container_name: backend
    environment:
      - REDIS=redis
      - DB_USERNAME=postgres
      - DB_PASSWORD=example
      - DB_NAME=postgres
      - DB_HOST=postgres
    depends_on:
      - redis
      - postgres
      
  frontend:
    build: frontend/
    image: frontend
    container_name: frontend
    depends_on:
      - backend
      
  redis:
    image: redis
    container_name: redis
    volumes:
        - /tmp/redisData:/data
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres
    container_name: db_postgres
    volumes:
        - ./database:/var/lib/postgresql/data
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 8000:8000
    depends_on:
      - frontend
      - backend
