version: "3.5"
services:

  backend:
    build: example-backend/
    image: backend
    ports:
      - 8080:8080
    container_name: backend
    environment:
      - REDIS_HOST=redis
      - REQUEST_ORIGIN=http://localhost:5000
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DATABASE=postgres #POSTGRES_DB
      - POSTGRES_HOST=postgres #service name
    depends_on:
      - redis
      - postgres
      
  frontend:
    build: example-frontend/
    image: frontend
    ports:
      - 5000:5000
    container_name: frontend
    depends_on:
      - backend
      
  redis:
    image: redis
    container_name: redis

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: example
    container_name: db_postgres


